[project]
name = "spd"
version = "0.0.1"
description = "Sparse Parameter Decomposition"
requires-python = ">=3.11,<3.13"
readme = "README.md"
dependencies = [
    "torch>2.4.1,<2.6.0",
    "torchvision",
    "pydantic",
    "wandb",
    "fire",
    "tqdm",
    "pytest",
    "ipykernel",
    "transformers",
    "jaxtyping",
    "einops",
    "matplotlib==3.9.1",  # Avoid frequent pyright errors with new matplotlib versions
    "numpy",
    "python-dotenv",
    "wandb<=0.17.7", # due to https://github.com/wandb/wandb/issues/8248
    "sympy",
    "streamlit",
    "streamlit-antd-components",
    "datasets",
    # added
    "numba",
    "scipy>=1.14.1",
    "scikit-learn",
    "umap-learn>=0.5.7",
    "muutils",
    "js-embedding-vis",
    "nbconvert",
]

[dependency-groups]
dev = [
    "ruff",
    "pytest",
    "pyright",
    # "pre-commit",
]


[tool.uv.sources]
    muutils = { git = "https://github.com/mivanit/muutils" }
    js_embedding_vis = { git = "https://github.com/mivanit/js-embedding-vis/"}

[tool.uv]
	default-groups = ["dev"]

[build-system]
	requires = ["hatchling"]
	build-backend = "hatchling.build"

[tool.ruff]
line-length = 100
fix = true

[tool.ruff.lint.per-file-ignores]
"notebooks/**" = [
    "E501", # Ignore line length in notebooks
    "E702", # Multiple statements on one line
]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = [
    "F722", # Incompatible with jaxtyping
    "E731", # I think lambda functions are fine in several places
]


[tool.ruff.format]
# Enable reformatting of code snippets in docstrings.
docstring-code-format = true

[tool.ruff.lint.isort]
known-third-party = ["wandb"]

[tool.pyright]
include = ["spd", "tests"]
exclude = ["**/wandb/**"]

strictListInference = true
strictDictionaryInference = true
strictSetInference = true
reportFunctionMemberAccess = true
reportUnknownParameterType = true
reportIncompatibleMethodOverride = true
reportIncompatibleVariableOverride = true
reportInconsistentConstructorType = true
reportOverlappingOverload = true
reportConstantRedefinition = true
reportImportCycles = true
reportPropertyTypeMismatch = true
reportMissingTypeArgument = true
reportUnnecessaryCast = true
reportUnnecessaryComparison = true
reportUnnecessaryContains = true
reportUnusedExpression = true
reportMatchNotExhaustive = true
reportShadowedImports = true
reportPrivateImportUsage = false
reportCallIssue = true

[tool.pytest.ini_options]
filterwarnings = [
    # https://github.com/google/python-fire/pull/447
    "ignore::DeprecationWarning:fire:59",
]